---
- name: install lamp server
  hosts: 
    - webserver
    - dbserver
  become: yes
  tasks: 
    - name: install apache2
      apt:
        name: apache2
        state: present
        update_cache : yes
      when: ansible_facts['os_family'] == "Debian" 
    - name: install php and mysql
      apt:
        name:
        - php
        - libapache2-mod-php
        - php-mysql
        state: present
      when: ansible_facts['os_family'] == "Debian"
    - name: install httpd
      yum: 
        name: httpd
        state: present
      when: ansible_facts['os_family'] == "RedHat"
    - name: install my sql
      yum:
        name:
        - php
        - php-mysql
        - php-fpm
        state: present
      notify: 
        - Restart Httpd
      when: ansible_facts['os_family'] == "RedHat"
    - name: copy the content
      copy:
        content: |
              <?php phpinfo()?>;
        dest: /var/www/html/info.php
      notify:
       - Restart Apache2 
       - Restart Httpd  
  handlers:
    - name: Restart Apache2
      service:
        name: apache2
        enabled: yes
        state: restarted 
      when: ansible_facts['os_family'] == "Debian"
    - name: Restart Httpd
      ansible.builtin.service:
        name: httpd
        enabled: yes
        state: restarted     
      when: ansible_facts['os_family'] == "RedHat"                                 
