---
- name: install lamp server
  hosts: 
    - webserver
    - dbserver 
  become: yes
  tasks: 
    - name: install apache
      package:
        name: "{{ package }}"
        state: present
    - name: install php modules
      package:
        name: "{{ php_packages }}"
        state: present
    - name: copy the content
      copy:
        content: |
              <?php phpinfo()?>;
        dest: "{{ info_location }}"
      notify:
       - Restart Apache  
  handlers:
    - name: Restart Apache
      service:
        name: "{{ package }}"
        enabled: yes
        state: restarted  
    - name: install lamp
         package: 
            name: java
    
                              
