---
- name: install lamp server
  hosts: 
    - webserver
    - dbserver
  become: yes
  tasks: 
    - name: install apache2
      apt:
        name: "{{ package }}"
        state: present
        update_cache : yes
      when: ansible_facts['os_family'] == "Debian" 
    - name: install php and mysql
      apt:
        name:
        - php
        - libapache2-mod-php
        - php-mysql
        state: present
      when: ansible_facts['os_family'] == "Debian"
    - name: install httpd
      yum: 
        name: "{{ package }}"
        state: present
      when: ansible_facts['os_family'] == "RedHat"
    - name: install my sql
      yum:
        name:
        - php
        - php-mysql
        - php-fpm
        state: present
      notify: 
        - Restart apache
      when: ansible_facts['os_family'] == "RedHat"
    - name: copy the content
      copy:
        content: |
              <?php phpinfo()?>;
        dest: "{{ info_location }}"
      notify:
       - Restart Apache  
  handlers:
    - name: Restart Apache
      service:
        name: "{{ package }}"
        enabled: yes
        state: restarted                              
