---
- name: install lamp server
  hosts: 
    - webserver
    - dbserver
  become: yes
  tasks: 
    - name: install apache2
      apt:
        name: apache2
        state: present
        update_cache : yes
      when: ansible_facts['os_family'] == "Debian" 
      when: ansible_facts['distribution_major_version'] == "20"
    - name: install php and mysql
      apt:
        name:
        - php
        - libapache2-mod-php
        - php-mysql
        state: present
      when: ansible_facts['os_family'] == "Debian"
      when: ansible_facts['distribution_major_version'] == "20"
    - name: install httpd
      yum: 
        name: httpd
        state: present
      when: ansible_facts['os_family'] == "RedHat"
      when: ansible_facts['distribution_major_version'] == "7"
    - name: install my sql
      yum:
        name:
        - php
        - php-mysql
        - php-fpm
        state: present
      notify: 
        - Restart httpd
      when: ansible_facts['os_family'] == "RedHat"
      when: ansible_facts['distribution_major_version'] == "7"
    - name: copy the content
      copy:
        content: |
              <?php phpinfo()?>;
        dest: /var/www/html/info.php
      notify:
       - Restart apache2 
       - Restart httpd  
  handlers:
    - name: Restart apache2
      ansible.builtin.service:
        name: apache2
        enabled: yes
        state: restarted 
      when: ansible_facts['os_family'] == "Debian" 
      when: ansible_facts['distribution_major_version'] == "20" 
    - name: Restart httpd
      ansible.builtin.service:
        name: httpd
        enabled: yes
        state: restarted     
      when: ansible_facts['os_family'] == "RedHat"
      when: ansible_facts['distribution_major_version'] == "7"                                  
